-- =============================================================================
-- Trace Mate — per-session spectate_token + harden start_trace_run
-- =============================================================================
-- Why
-- ────
-- The first cut of admin spectating used `tracewatch:${userId}` as the
-- realtime signaling channel. Realtime channels are not authenticated by
-- default — anyone holding the public anon key plus the user's UUID could
-- subscribe and become a "viewer", at which point the broadcaster would
-- ship them the camera feed (1:1 race notwithstanding). UUIDs aren't
-- normally exposed publicly, but this is security-by-obscurity.
--
-- Fix: use a server-issued random `spectate_token` (uuid v4, 122 bits of
-- entropy) per `trace_session_runs` row. The channel becomes
-- `tw:${spectate_token}`. The token is:
--   - Generated server-side at start_trace_run time.
--   - Returned to the user's own client (so /trace can broadcast on it).
--   - Readable to admins via service-role join in admin-list-users.
--   - NOT readable by other users — the trace_session_runs_self_read RLS
--     policy already restricts SELECT to `auth.uid() = user_id`.
-- A new session = new token, so a leaked token only buys access to the
-- session it was issued for, and only while that session is live.
--
-- start_trace_run's return type changes from uuid → jsonb so the client
-- can pick up both `run_id` and `spectate_token` in one round trip. We
-- drop+recreate (CREATE OR REPLACE can't widen the return type).
--
-- Idempotent — safe to re-run.
-- =============================================================================

alter table public.trace_session_runs
  add column if not exists spectate_token uuid not null default gen_random_uuid();

-- Useful when the admin endpoint joins by run id; small table, but a
-- partial index keeps the open-runs lookup tight.
create index if not exists trace_session_runs_open_token_idx
  on public.trace_session_runs (id)
  where ended_at is null;

-- Drop the old uuid-returning version so we can change the return type.
-- The signature (text param with default null) is unchanged so client
-- callers don't need to pass anything new.
drop function if exists public.start_trace_run(text);

create function public.start_trace_run(p_image_label text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid   uuid := auth.uid();
  v_now   timestamptz := now();
  v_id    uuid;
  v_token uuid;
  v_label text;
begin
  if v_uid is null then
    raise exception 'Not authenticated';
  end if;

  v_label := nullif(trim(coalesce(p_image_label, '')), '');
  if v_label is not null and length(v_label) > 200 then
    v_label := left(v_label, 200);
  end if;

  -- Reconcile any stragglers from prior crashes / hard kills before we
  -- open a fresh row. Same behaviour as the previous version.
  perform public.reconcile_trace_runs_for_user(v_uid, 0);

  -- Token is generated by the column default (gen_random_uuid). The
  -- INSERT … RETURNING grabs both fields in one shot.
  insert into public.trace_session_runs (user_id, image_label)
  values (v_uid, v_label)
  returning id, spectate_token into v_id, v_token;

  update public.profiles
     set trace_sessions = trace_sessions + 1,
         first_trace_at = coalesce(first_trace_at, v_now),
         last_trace_at  = v_now,
         last_seen_at   = v_now,
         current_page   = 'trace',
         current_image_label = v_label,
         current_run_id = v_id
   where id = v_uid;

  return jsonb_build_object(
    'run_id',          v_id,
    'spectate_token',  v_token
  );
end $$;

revoke all on function public.start_trace_run(text) from public;
grant execute on function public.start_trace_run(text) to authenticated;
